name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}   # Asegúrate de que este secreto esté configurado correctamente
        password: ${{ secrets.DOCKER_PASSWORD }}   # Asegúrate de que este secreto esté configurado correctamente
   
    - name: List files
      run: ls -la

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .                                   # Asegúrate de que tu Dockerfile esté en la raíz o ajusta la ruta
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/docker-demo:latest
